name = "safadasso"
main = "functions/main.js"
compatibility_date = "2025-04-18"

# Configuração simples sem rotas personalizadas
# O Cloudflare Pages gerencia as rotas automaticamente

[site]
bucket = "./"

[triggers]
crons = [] 