name = "safadasso"
main = "functions/main.js"
compatibility_date = "2025-04-18"

# Configuração de rotas para Workers
[[routes]]
pattern = "/agenda*"
script = "safadasso"

[site]
bucket = "./"

[triggers]
crons = [] 